set(
        xsdnn_layers_src
        "${XSROOT_SRC}/layers/layer.cc"
        "${XSROOT_SRC}/layers/fully_connected.cc"
        "${XSROOT_SRC}/layers/input.cc"
        "${XSROOT_SRC}/layers/output.cc"
        "${XSROOT_SRC}/layers/add.cc"
        "${XSROOT_SRC}/layers/abs.cc"
        "${XSROOT_SRC}/layers/acos.cc"
        "${XSROOT_SRC}/layers/flatten.cc"
        "${XSROOT_SRC}/layers/max_pooling.cc"
        "${XSROOT_SRC}/layers/global_average_pooling.cc"
        "${XSROOT_SRC}/layers/mul.cc"
        "${XSROOT_SRC}/layers/reshape.cc"
        "${XSROOT_SRC}/layers/convolution.cc"
        "${XSROOT_SRC}/layers/layer_register.cc"
)