set(mmpack_common_src
        ${MMPACK_ROOT}/allocator.cc
        ${MMPACK_ROOT}/activation.cc
        ${MMPACK_ROOT}/sgemm.cc
        ${MMPACK_ROOT}/sdot.cc
        ${MMPACK_ROOT}/smuladd.cc
        ${MMPACK_ROOT}/sconv.cc
        ${MMPACK_ROOT}/sadd.cc
        )